### ISSUE TITLE
Contig-taxid file does not seem to have two cols with the seqid in the first col and taxid in the second col

### ISSUE THREAD

**Issue by pkfsantos** [blaxterlab/blobology#8]
Hello everyone,
I am getting the follow error:
"Contig-taxid file random10k.example_scaffolds.fa.nt.1e-5.megablast does not seem to have two cols with the seqid in the first col and taxid in the second col at /home/pkfs/blobology/gc_cov_annotate.pl line 58, <$filehandle> line 1.
Error in file(file, "rt") : não é possível abrir a conexão
Calls: read.delim -> read.table -> file
Além disso: Warning message:
In file(file, "rt") :
  não foi possível abrir o arquivo 'blobplot.txt': Arquivo ou diretório não encontrado
Execução interrompida
"
When I open the created file ( "random10k.example_scaffolds.fa.nt.1e-5.megablast"), I have:
"372284	N/A
410910	N/A
281600	N/A
3303361	N/A
1790197	N/A
3226893	N/A
(...)
"
Do you have any ideia how can I solve this problem?
Best regards,

Priscila

**Comment by Rebeccabengtsson** [comment]
Hello Priscila, 

blastn for some reason does not like the configuration of  '6 qseqid staxids' from the line 

blastn -task megablast -query $RND_ASSEMBLY -db $BLASTDB/nt -evalue 1e-5 -num_threads $NUMPROC -max_target_seqs 1 -outfmt '6 qseqid staxids' -out $RND_ASSEMBLY.nt.1e-5.megablast

I removed the s from staxids so the new configuration is '6 qseqid staxid' and it worked.

Rebecca

**Comment by DRL** [comment]
Hi both, 

the blobology pipeline  is no longer maintained and its use is not encouraged...

You might want to check out BlobTools:
- https://github.com/DRL/blobtools
- https://blobtools.readme.io/docs
 
cheers,

dom

**Comment by kalonji08** [comment]
> Hello Priscila,
> 
> blastn for some reason does not like the configuration of '6 qseqid staxids' from the line
> 
> blastn -task megablast -query $RND_ASSEMBLY -db $BLASTDB/nt -evalue 1e-5 -num_threads $NUMPROC -max_target_seqs 1 -outfmt '6 qseqid staxids' -out $RND_ASSEMBLY.nt.1e-5.megablast
> 
> I removed the s from staxids so the new configuration is '6 qseqid staxid' and it worked.
> 
> Rebecca

Hi @RJBeng I hope you are well. I have encountered the same issue, would you please expand on how you achieved this ? I'm still new and would really like to get this analysis. Thank you :)
